{
 "title": "Cloudflare Zone Analytics (Free Tier)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "zone",
    "query": "label_values(cloudflare_zone_requests_total, zone)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range])"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__range])"
    }
   ]
  },
  {
   "title": "Requests / minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_requests_total{zone=~\"$zone\"}"
    }
   ]
  },
  {
   "title": "Bandwidth / minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_bandwidth_total{zone=~\"$zone\"}"
    }
   ]
  },
  {
   "title": "Total Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum_over_time(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__range])"
    }
   ]
  },
  {
   "title": "Uniques / minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cloudflare_zone_uniques_total{zone=~\"$zone\"}"
    }
   ]
  },
  {
   "title": "Unique Visitors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudflare_zone_uniques_total{zone=~\"$zone\"}",
     "legendFormat": "visitors"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Requests / minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "total"
    },
    {
     "expr": "cloudflare_zone_requests_cached{zone=~\"$zone\"}",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "Requests per Country / Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudflare_zone_requests_country{zone=~\"$zone\"} > 0",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Requests / Minute (status codes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudflare_zone_requests_status{zone=~\"$zone\", status!~\"5..\"} ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests / Minute (status codes not 2XX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudflare_zone_requests_status{zone=~\"$zone\", status!~\"2..\"} ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 40 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "cloudflare_zone_requests_cached{zone=~\"$zone\"} / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "(cloudflare_zone_requests_total{zone=~\"$zone\"} - cloudflare_zone_requests_cached{zone=~\"$zone\"}) / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "uncached"
    }
   ]
  },
  {
   "title": "Requests SSL",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 40 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "cloudflare_zone_requests_ssl_encrypted{zone=~\"$zone\"} / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "encrypted"
    },
    {
     "expr": "( cloudflare_zone_requests_total{zone=~\"$zone\"} - cloudflare_zone_requests_ssl_encrypted{zone=~\"$zone\"}  ) / cloudflare_zone_requests_total{zone=~\"$zone\"}",
     "legendFormat": "unencrypted"
    }
   ]
  },
  {
   "title": "Errors / Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cloudflare_zone_requests_status{zone=~\"$zone\", status=~\"5..\"} ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__range])",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Requests Status Codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(cloudflare_zone_requests_status{zone=~\"$zone\"}[$__range])",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth / minute",
     "type": "graph",
     "gridPos": { "h": 10, "w": 23, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "cloudflare_zone_bandwidth_total{zone=~\"$zone\"}",
       "legendFormat": "total"
      },
      {
       "expr": "cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}",
       "legendFormat": "cached"
      }
     ]
    },
    {
     "title": "Cached Bandwidth",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "cloudflare_zone_bandwidth_cached{zone=~\"$zone\"} / cloudflare_zone_bandwidth_total{zone=~\"$zone\"}",
       "legendFormat": "cached"
      },
      {
       "expr": "(cloudflare_zone_bandwidth_total{zone=~\"$zone\"} - cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}) / cloudflare_zone_bandwidth_total{zone=~\"$zone\"}",
       "legendFormat": "uncached"
      }
     ]
    }
   ]
  },
  {
   "title": "Threats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threats / minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cloudflare_zone_threats_total{zone=~\"$zone\"}",
       "legendFormat": "{{zone}}/threats"
      }
     ]
    },
    {
     "title": "Threats / country",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cloudflare_zone_threats_country{zone=~\"$zone\"}",
       "legendFormat": "{{country}}/threats"
      }
     ]
    }
   ]
  }
 ]
}